services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
    - ./.env
    environment:
    - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - n8n
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
    - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - N8N_EMAIL_MODE=smtp
    - N8N_SMTP_HOST=localhost
    - N8N_SMTP_PORT=1025
    - N8N_SMTP_USER=user
    - N8N_SMTP_PASS=password
    - N8N_SMTP_SENDER=sender@example.com
    - N8N_SMTP_SSL=false
    volumes:
    - ./n8n-data:/home/node/.n8n
    depends_on:
    - postgres

volumes:
  postgres_data: